sudo: false

language: cpp

compiler: gcc

os: linux

addons:
  apt:
    packages:
    - libboost-all-dev
    - libpoco-dev
    - libgcrypt20
    - libgcrypt-dev

script:
- mkdir build && cd build && cmake .. && make

